config/routes.rb
Rails.application.routes.draw do
  resources :appts

  get 'static_pages/home'

  resources :slots

  resources :appts

  resources :appointments

  resources :physicians

  resources :physician_statuses

  resources :patients

  resources :diagnostic_codes

   root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:home)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %><br>
    <%= f.text_field :home %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing static_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/home.html.erb
<br>
<h2> Please select the desired action from the menu above</h2>

app/views/static_pages/index.html.erb
<h1>Listing static_pages</h1>

<table>
  <thead>
    <tr>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= static_page.home %></td>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static page', new_static_page_path %>

app/views/static_pages/new.html.erb
<h1>New static_page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home:</strong>
  <%= @static_page.home %>
</p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>