config/routes.rb
Rails.application.routes.draw do
  resources :appts

  get 'static_pages/home'

  resources :slots

  resources :appts

  resources :appointments

  resources :physicians

  resources :physician_statuses

  resources :patients

  resources :diagnostic_codes

   root 'static_pages#home'

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appts
  belongs_to :patient

  validates_numericality_of :diag_cost
  validates_presence_of :diag_code_name, :dag_code_num, :diag_cost

end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, only: [:show, :edit, :update, :destroy]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.order("dag_code_num").page(params[:page])
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_code }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_code }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url, notice: 'Diagnostic code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_code
      @diagnostic_code = DiagnosticCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_code_params
      params.require(:diagnostic_code).permit(:dag_code_num, :diag_code_name, :diag_cost)
    end
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for(@diagnostic_code) do |f| %>
  <% if @diagnostic_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h2>

      <ul>
      <% @diagnostic_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Diagnostic Code Number' %><br>
    <%= f.text_field :dag_code_num %>
  </div>
  <div class="field">
    <%= f.label 'Diagnostic Code Name' %><br>
    <%= f.text_field :diag_code_name %>
  </div>
  <div class="field">
    <%= f.label 'Diagnostic Cost' %><br>
    <%= f.text_field :diag_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnostic_codes/edit.html.erb
<h1>Editing diagnostic_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic_code %> |
<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/index.html.erb
<h1>Listing Diagnostic Codes</h1>
<%= paginate @diagnostic_codes %>
<table>
  <thead>
    <tr>
      <th>Diagnostic code number</th>
      <th>Diagnostic code name</th>
      <th>Diagnostic cost</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
      <tr>
        <td><%= diagnostic_code.dag_code_num %></td>
        <td><%= diagnostic_code.diag_code_name %></td>
        <td><%= number_to_currency(diagnostic_code.diag_cost) %></td>
        <td><%= link_to 'Show', diagnostic_code %></td>
        <td><%= link_to 'Edit', edit_diagnostic_code_path(diagnostic_code) %></td>
        <td><%= link_to 'Destroy', diagnostic_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnostic code', new_diagnostic_code_path %>

app/views/diagnostic_codes/new.html.erb
<h1>New diagnostic code</h1>
<h3>All Fields are Mandatory</h3>
<%= render 'form' %>

<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing diagnostic code:</h1>

<p>
  <strong>Diagnostic code number:</strong>
  <%= @diagnostic_code.dag_code_num %>
</p>

<p>
  <strong>Diagnostic code name:</strong>
  <%= @diagnostic_code.diag_code_name %>
</p>

<p>
  <strong>Diagnostic cost:</strong>
  <%= number_to_currency(@diagnostic_code.diag_cost) %>
</p>

<%= link_to 'Edit', edit_diagnostic_code_path(@diagnostic_code) %> |
<%= link_to 'Back', diagnostic_codes_path %>