config/routes.rb
Rails.application.routes.draw do
  resources :appts

  get 'static_pages/home'

  resources :slots

  resources :appts

  resources :appointments

  resources :physicians

  resources :physician_statuses

  resources :patients

  resources :diagnostic_codes

   root 'static_pages#home'

end

app/controllers/physician_statuses_controller.rb
class PhysicianStatusesController < ApplicationController
  before_action :set_physician_status, only: [:show, :edit, :update, :destroy]

  # GET /physician_statuses
  # GET /physician_statuses.json
  def index
    @physician_statuses = PhysicianStatus.all
  end

  # GET /physician_statuses/1
  # GET /physician_statuses/1.json
  def show
  end

  # GET /physician_statuses/new
  def new
    @physician_status = PhysicianStatus.new
  end

  # GET /physician_statuses/1/edit
  def edit
  end

  # POST /physician_statuses
  # POST /physician_statuses.json
  def create
    @physician_status = PhysicianStatus.new(physician_status_params)

    respond_to do |format|
      if @physician_status.save
        format.html { redirect_to @physician_status, notice: 'Physician status was successfully created.' }
        format.json { render :show, status: :created, location: @physician_status }
      else
        format.html { render :new }
        format.json { render json: @physician_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physician_statuses/1
  # PATCH/PUT /physician_statuses/1.json
  def update
    respond_to do |format|
      if @physician_status.update(physician_status_params)
        format.html { redirect_to @physician_status, notice: 'Physician status was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician_status }
      else
        format.html { render :edit }
        format.json { render json: @physician_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physician_statuses/1
  # DELETE /physician_statuses/1.json
  def destroy
    @physician_status.destroy
    respond_to do |format|
      format.html { redirect_to physician_statuses_url, notice: 'Physician status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician_status
      @physician_status = PhysicianStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_status_params
      params.require(:physician_status).permit(:status_name)
    end
end

app/helpers/physician_statuses_helper.rb
module PhysicianStatusesHelper
end

app/views/physician_statuses/_form.html.erb
<%= form_for(@physician_status) do |f| %>
  <% if @physician_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician_status.errors.count, "error") %> prohibited this physician_status from being saved:</h2>

      <ul>
      <% @physician_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_name %><br>
    <%= f.text_field :status_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physician_statuses/edit.html.erb
<h1>Editing physician status</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician_status %> |
<%= link_to 'Back', physician_statuses_path %>

app/views/physician_statuses/index.html.erb
<h1>Listing Physician Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Physician status name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @physician_statuses.each do |physician_status| %>
      <tr>
        <td><%= physician_status.status_name %></td>
        <td><%= link_to 'Show', physician_status %></td>
        <td><%= link_to 'Edit', edit_physician_status_path(physician_status) %></td>
        <td><%= link_to 'Destroy', physician_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician status', new_physician_status_path %>

app/views/physician_statuses/new.html.erb
<h1>New physician_status</h1>

<%= render 'form' %>

<%= link_to 'Back', physician_statuses_path %>

app/views/physician_statuses/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing physician status:</h1>

<p>
  <strong>Status name:</strong>
  <%= @physician_status.status_name %>
</p>

<%= link_to 'Edit', edit_physician_status_path(@physician_status) %> |
<%= link_to 'Back', physician_statuses_path %>