config/routes.rb
Rails.application.routes.draw do
  resources :appts

  get 'static_pages/home'

  resources :slots

  resources :appts

  resources :appointments

  resources :physicians

  resources :physician_statuses

  resources :patients

  resources :diagnostic_codes

   root 'static_pages#home'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appts
  has_many :physicians, through: :appts
  has_many :slots, through: :appts
  has_many :diagnostic_codes, through: :appts

  validates_presence_of :pat_f_name, :pat_l_name, :pat_email
  validates_format_of :pat_email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :pat_email, :case_sensitive => false, :message => "Email is already registered. Please enter a new email"
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all.order(:pat_l_name)
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:pat_f_name, :pat_l_name, :pat_email)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'First Name' %><br>
    <%= f.text_field :pat_f_name %>
  </div>
  <div class="field">
    <%= f.label 'Last Name' %><br>
    <%= f.text_field :pat_l_name %>
  </div>
  <div class="field">
    <%= f.label 'Email Address' %><br>
    <%= f.text_field :pat_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Patient first name</th>
      <th>Patient last name</th>
      <th>Patient email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.pat_f_name %></td>
        <td><%= patient.pat_l_name %></td>
        <td><%= patient.pat_email %></td>
        <td><%= link_to 'Patient Info & Appointment Summary', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>
<h3>All Fields are Mandatory</h3>
<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Showing patient details:</h1>

<p>
  <strong>Patient first name:</strong>
  <%= @patient.pat_f_name %>
</p>

<p>
  <strong>Patient last name:</strong>
  <%= @patient.pat_l_name %>
</p>

<p>
  <strong>Patient email:</strong>
  <%= @patient.pat_email %>
</p>
<br>
<h1> Patient Appointment History:</h1>
<table>

  <tr>
    <th>Appt Date</th>
    <th>Time Slot</th>
    <th>Reason</th>
    <th>Physician</th>
    <th>Diagnostic</th>
    <th>Physician Notes</th>
    <th>Diagnostic Cost</th>
    <th>Actions</th>
  </tr>

  <% @patient.appts.order('apt_date').reverse_order.each do |a| %>
  <tr>
    <td> <%=a.apt_date %> </td>
    <td> <%=a.slot.time_block %> </td>
    <td> <%=a.reason %> </td>
    <td> <%=a.physician.phy_name %> </td>
    <td> <%=a.diagnostic_code.diag_code_name rescue '' %> </td>
    <td> <%=a.phy_notes %> </td>
    <td> <%=number_to_currency(a.diagnostic_code.diag_cost) rescue '' %> </td>
    <td><%=link_to 'Modify Appointment', edit_appt_path(a) %></td>

  </tr>
  <%end%>
</table>



<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>